export const CHANGE_PLAYBACK_RATE = 'CHANGE_PLAYBACK_RATE'
export const MAKE_RESTART_BAR_CURRENT = 'MAKE_RESTART_BAR_CURRENT'
export const TOGGLE_IS_CREATING_REGION = 'TOGGLE_IS_CREATING_REGION'
export const TOGGLE_IS_PAUSED = 'TOGGLE_IS_PAUSED'
